# Define the docker hub image
# This image comes with Node.js and NPM already installed
FROM node:latest

# Create app directory to hold the application code inside the image
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY package.json /app

# Bundle app source
COPY . /app

EXPOSE 8081

RUN npm install
CMD npm start
