# Define the docker hub image
FROM node:latest

# Create app directory
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY package.json /app

# Bundle app source
COPY . /app

EXPOSE 8081

RUN npm install
CMD npm start
